version: '3.8'
services:
  tauri:
    container_name: "tauri"
    build: ./env/rust
    tty: true
    environment:
      - DISPLAY=$DISPLAY
      - WAYLAND_DISPLAY=$WAYLAND_DISPLAY
      - XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR
      - PULSE_SERVER=$PULSE_SERVER
    volumes: 
      - ./app:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /mnt/wslg:/mnt/wslg
    ports:
      - 6000:6000
      - 1420:1420
    networks:
      - tauri-net

networks:
  tauri-net:
    driver: bridge
